# [menu]
[[main]]
identifier = "about"
name = "About"
title = "About"
url = "/about"
weight = -110
# [[menu.main]]
#   identifier = "research"
#   name = "Research"
#   title = "Research"
#   url = "/research"
# weight = -100
[[main]]
  identifier = "contact"
  name = "Contact"
  title = "Contact"
  url = "/contact"
  weight = -90
# [[menu.main]]
#   identifier = "Students"
#   name = "Students"
#   title = "Students"
#   url = "/students/"
#   weight = -90
# [[menu.main]]
#   identifier = "Categories"
#   name = "Categories"
#   title = "Categories"
#   url = "/categories/"
#   weight = -80