# [menu]
[[main]]
identifier = "about"
name = "About"
title = "About"
url = "/about"
weight = -110
# [[menu.main]]
#   identifier = "research"
#   name = "Research"
#   title = "Research"
#   url = "/research"
# weight = -100
[[main]]
  identifier = "contact"
  name = "Contact"
  title = "Contact"
  url = "/contact"
  weight = -90
[[main]]
  identifier = "Resources"
  name = "Resources"
  title = "Resources"
  url = "/resources/"
  weight = -100

